/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2021-07-28 11:44:07
 */
import { AssetEnvelope } from "./mixer/AssetEnvelope";

/**
 *  Common sequence of states:
 *  Silence => FadingIn => PlayingAsset => FadingOut => Silence
 */
